---
name: "Bump version"
"on":
  pull_request:
    types:
    - "closed"
    branches:
    - "main"
jobs:
  build:
    if: "github.event.pull_request.merged == true"
    runs-on: "ubuntu-22.04"
    steps:
    - uses: "actions/checkout@v4"
      with:
        ref: "${{ github.event.pull_request.merge_commit_sha }}"
        fetch-depth: "0"
    - name: "Bump version and push tag"
      uses: "anothrNick/github-tag-action@1.69.0"
      env:
        GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"
        WITH_V: true
        DEFAULT_BUMP: "minor"
        RELEASE_BRANCHES: "main"
